export const PROJECTS = [
  {
    id: 1,
    name: 'NATIONAL ASSEMBLY BUILDING',
    authority: 'BANGLADESH PUBLIC WORKS DEPARTMENT',
    capacity: '2500 TR',
  },
  {
    id: 2,
    name: 'SENA KALYAN BHABAN',
    authority: 'SENA KALYAN SANGSTHA',
    capacity: '1060 TR',
  },
  {
    id: 3,
    name: 'EASTERN HOUSING PLAZA',
    authority: 'EASTERN HOUSING LIMITED',
    capacity: '520 TR',
  },
  {
    id: 4,
    name: "INTERNATIONAL CONFERENCE CENTRE (ICC) & PRIME MINISTER'S OFFICE",
    authority: 'BANGLADESH PUBLIC WORKS DEPARTMENT',
    capacity: '300 TR',
  },
  {
    id: 5,
    name: 'WORLD BANK RESIDENT MISSION',
    authority: 'WORLD BANK RESIDENT MISSION',
    capacity: '250 TR',
  },
  {
    id: 6,
    name: 'BEXIMCO SYNTHETIC LIMITED',
    authority: 'BEXIMCO GROUP',
    capacity: '768 TR',
  },
  {
    id: 7,
    name: 'JAMUNA GUEST HOUSE',
    authority: 'CONCORD ENGINEERS & CONSTRUCTION LTD.',
    capacity: '110 TR',
  },
  {
    id: 8,
    name: 'BANGLADESH BANK HEAD OFFICE',
    authority: 'BANGLADESH BANK',
    capacity: '2400 TR',
  },
  {
    id: 9,
    name: 'NATIONAL INDOOR STADIUM',
    authority: 'NATIONAL SPORTS COUNCIL',
    capacity: '800 TR',
  },
  {
    id: 10,
    name: 'BRAC CENTRE',
    authority: 'BRAC BANGLADESH',
    capacity: '525 TR',
  },
  {
    id: 11,
    name: 'HOLDING LOUNGE & CONNECTING CORRIDOR FOR BOARDING BRIDGE AZIA INTERNATIONAL AIRPORT',
    authority: 'CIVIL AVIATION AUTHORITY OF BANGLADESH',
    capacity: '300 TR',
  },
  {
    id: 12,
    name: 'DR. SHAMSUL ALAM KHAN (MILON) MEMORIAL AUDITORIUM',
    authority: 'BANGLADESH PUBLIC WORKS DEPARTMENT',
    capacity: '168 TR',
  },
  {
    id: 13,
    name: 'IDB BHABAN',
    authority: 'CONCORD ENGINEERS & CONSTRUCTION LTD.',
    capacity: '1600 TR',
  },
  {
    id: 14,
    name: 'EMBASSY OF UNITED STATES OF AMERICA',
    authority: 'DAELIM CONSTRUCTION COMPANY LTD.',
    capacity: '340 TR',
  },
  {
    id: 15,
    name: 'SMC TOWER',
    authority: 'SOCIAL MARKETING COMPANY, BANGLADESH',
    capacity: '700 TR',
  },
  {
    id: 16,
    name: 'CONCORD TWIN TOWER SHOPPING COMPLEX',
    authority: 'CONCORD ENGINEERS & CONSTRUCTION LTD.',
    capacity: '600 TR',
  },
  {
    id: 17,
    name: 'SHINEPUKUR CERAMICS FACTORY',
    authority: 'SHINEPUKUR CERAMICS LTD.',
    capacity: '69 TR',
  },
  {
    id: 18,
    name: 'ARIF KNIT SPINNING LTD.',
    authority: 'N.R. GROUP',
    capacity: '1800 TR',
  },
  {
    id: 19,
    name: 'MONNO TEXTILE',
    authority: 'MONNO GROUP',
    capacity: '1000 TR',
  },
  {
    id: 20,
    name: 'ORS FACTORY SMC',
    authority: 'SOCIAL MARKETING COMPANY',
    capacity: '300 TR',
  },
  {
    id: 21,
    name: 'EASTERN PLUS SHOPPING COMPLEX',
    authority: 'EASTERN HOUSING LIMITED',
    capacity: '600 TR',
  },
  {
    id: 22,
    name: 'ESSENTIAL DUGS COMPANY LTD.',
    authority: 'ESSENTIAL DUGS COMPANY LTD',
    capacity: '130 TR',
  },
  {
    id: 23,
    name: 'CHANCERY BUILDING OF US EMBASSY',
    authority: 'US EMBASSY',
    capacity: '300 TR',
  },
  {
    id: 24,
    name: 'GSO OFFICE OF US EMBASSY',
    authority: 'US EMBASSY',
    capacity: '180 TR',
  },
  {
    id: 25,
    name: 'CANADIAN EMBASSY',
    authority: 'CANADIAN EMBASSY',
    capacity: '220 TR',
  },
  {
    id: 26,
    name: 'INCEPTA PHARMACEUTICAL LTD.',
    authority: 'IMPRESS GROUP',
    capacity: '420 TR',
  },
  {
    id: 27,
    name: 'CHANNEL-I',
    authority: 'IMPRESS GROUP',
    capacity: '420 TR',
  },
  {
    id: 28,
    name: 'MARS SPINNING',
    authority: 'MARS GROUP',
    capacity: '1800 TR',
  },
  {
    id: 29,
    name: 'MEBPOY',
    authority: 'MOHAMUD ILIAS BROTHERS LTD.',
    capacity: '520 TR',
  },
  {
    id: 30,
    name: 'AKTHER – UZ – ZAMAN SHOPPING COMPLEX CUM COMMERCIAL BUILDING',
    authority: 'AKTHER – UZ – ZAMAN GROUP',
    capacity: '1000 TR',
  },
  {
    id: 31,
    name: 'SANMAR SUPER OIL',
    authority: 'SANMAR GROUP',
    capacity: '400 TR',
  },
  {
    id: 32,
    name: 'BANGLADESH BANK ANNEX BUILDING',
    authority: 'BANGLADESH BANK',
    capacity: '300 TR',
  },
  {
    id: 33,
    name: 'NATIONAL THEATRE',
    authority: 'BANGLADESH PUBLIC WORKS DEPARTMENT',
    capacity: '250 TR',
  },
  {
    id: 34,
    name: 'BAY GALLERIA',
    authority: 'BAY DEVELOPMENT',
    capacity: '652 TR',
  },
  {
    id: 35,
    name: 'BEACON PHARMA',
    authority: 'ORION GROUP',
    capacity: '750 TR',
  },
  {
    id: 36,
    name: 'SQUARE HOSPATIAL LTD.',
    authority: 'SQUARE HOSPATIAL LTD.',
    capacity: '2000 TR',
  },
  {
    id: 37,
    name: 'BANGLADESH BANK TRAINING ACADEMY',
    authority: 'BANGLADESH BANK',
    capacity: '300 TR',
  },
  {
    id: 38,
    name: 'SHADHINOTASTAMBA',
    authority: 'BANGLADESH PUBLIC WORKS DEPARTMENT',
    capacity: '300 TR',
  },
  {
    id: 39,
    name: 'JANATA BANK',
    authority: 'JANATA BANK',
    capacity: '1300 TR',
  },
  {
    id: 40,
    name: 'NORTH SOUTH UNIVERSITY',
    authority: 'NORTH SOUTH UNIVERSITY',
    capacity: '2750 TR',
  },
  {
    id: 41,
    name: 'ALICO BUILDING',
    authority: 'AMERICAN LIFE INSURANCE COMPANY',
    capacity: '107 TR',
  },
  {
    id: 42,
    name: 'ARMED FORCES INSTITUTE OF PATHOLOGY',
    authority: 'BANGLADESH ARMY',
    capacity: '120 TR',
  },
  {
    id: 43,
    name: 'DOREEN TOWER',
    authority: 'DOREEN GROUP',
    capacity: '894 TR',
  },
  {
    id: 44,
    name: 'BEXIMCO PHARMA',
    authority: 'BEXIMCO GROUP',
    capacity: '730 TR',
  },
  {
    id: 45,
    name: 'UNITED HOSPITAL LTD.',
    authority: 'UNITED HOSPITAL LTD.',
    capacity: '600 TR',
  },
  {
    id: 46,
    name: 'UK EMBASSY',
    authority: 'UK EMBASSY',
    capacity: '236 TR',
  },
  {
    id: 47,
    name: 'SIRAJ SPECIALIZED HOSPITAL & RESEARCH CENTER',
    authority: 'SIRAJ SPECIALIZED HOSPITAL & RESEARCH CENTER',
    capacity: '500 TR',
  },
  {
    id: 48,
    name: 'SQ CELSIUS LTD',
    authority: 'SQ GROUP',
    capacity: '400 TR',
  },
  {
    id: 49,
    name: "INTERNATIONAL CONFERENCE CENTRE (ICC) & PRIME MINISTER'S OFFICE",
    authority: 'BANGLADESH PUBLIC WORKS DEPARTMENT',
    capacity: '300 TR',
  },
  {
    id: 50,
    name: 'GULSHAN CENTER POINT',
    authority: 'UNITED GROUP',
    capacity: '600 TR',
  },
  {
    id: 51,
    name: 'NATIONAL ACHIEVE BHABAN',
    authority: 'BANGLADESH PUBLIC WORKS DEPARTMENT',
    capacity: '100 TR',
  },
  {
    id: 52,
    name: "INTERNATIONAL CONFERENCE CENTRE (ICC) & PRIME MINISTER'S OFFICE",
    authority: 'BANGLADESH PUBLIC WORKS DEPARTMENT',
    capacity: '150 TR',
  },
  {
    id: 53,
    name: 'ECO FAB LIMITED',
    authority: 'VIYELLATEX GROUP',
    capacity: '600 TR',
  },
  {
    id: 54,
    name: 'ARGON SPINNING MILLS',
    authority: 'ARGON DENIM LTD.',
    capacity: '600 TR',
  },
  {
    id: 55,
    name: 'R-PAC BANGLADESH LTD',
    authority: 'R-PAC (BANGLADESH) LTD.',
    capacity: '600 TR',
  },
  {
    id: 56,
    name: 'BRAC CENTRE',
    authority: 'BRAC BANGLADESH',
    capacity: '300 TR',
  },
  {
    id: 57,
    name: 'MATIN SPINNING',
    authority: 'DBL GROUP',
    capacity: '2000 TR',
  },
  {
    id: 58,
    name: 'JAPAN GARDEN CITY (JGCL)',
    authority: 'JAPAN GARDEN CITY (JGCL)',
    capacity: '400 TR',
  },
  {
    id: 59,
    name: 'SAIHAM TOWER',
    authority: 'SAIHAM GROUP',
    capacity: '600 TR',
  },
  {
    id: 60,
    name: 'ACI HEALTH CARE LTD.',
    authority: 'ACI GROUP',
    capacity: '2025 TR',
  },
  {
    id: 61,
    name: 'BANGABANDHU SATELLITE LAUNCHING PROJECT OF BTRC',
    authority: 'SPECTRA INTERNATIONAL LIMITED',
    capacity: '600 TR',
  },
  {
    id: 62,
    name: 'UNIVERSE SYNTHETIC FIBER LTD.',
    authority: 'BANG JIN GROUP',
    capacity: '300 TR',
  },
  {
    id: 63,
    name: 'SHIMANTO SQUARE',
    authority: 'BANGLADESH BORDER GUARD (BGB)',
    capacity: '800 TR',
  },
  {
    id: 64,
    name: 'SHIMANTOSHAMBHAR',
    authority: 'BANGLADESH BORDER GUARD (BGB)',
    capacity: '1250 TR',
  },
  {
    id: 65,
    name: 'ARIF KNIT SPINNING LTD.',
    authority: 'N.R. GROUP',
    capacity: '1400 TR',
  },
  {
    id: 66,
    name: 'GULSHAN CENTER POINT',
    authority: 'UNITED GROUP',
    capacity: '200 TR',
  },
  {
    id: 67,
    name: 'BALAKA BHABAN',
    authority: 'BIMAN BANGLADESH AIRLINES LTD.',
    capacity: '250 TR',
  },
  {
    id: 68,
    name: 'ESKAYEF PHARMACEUTICALS LIMITED',
    authority: 'ESKAYEF PHARMACEUTICALS LIMITED',
    capacity: '850 TR',
  },
  {
    id: 69,
    name: 'SAVER CANTONMENT SUPER MARKET',
    authority: 'CANTONMENT BOARD, SAVER, DHAKA',
    capacity: '2500 TR',
  },
  {
    id: 70,
    name: 'BIMAN ENGINEERING HANGER COMPLEX',
    authority: 'BIMAN BANGLADESH AIRLINES LTD.',
    capacity: '80 TR',
  },
  {
    id: 71,
    name: 'NORTH SOUTH UNIVERSITY',
    authority: 'NORTH SOUTH UNIVERSITY',
    capacity: '330 TR',
  },
  {
    id: 72,
    name: 'SQHL',
    authority: 'SQ GROUP',
    capacity: '40 TR',
  },
  {
    id: 73,
    name: 'ESKAYEF PHARMACEUTICALS LIMITED',
    authority: 'ESKAYEF PHARMACEUTICALS LIMITED',
    capacity: '600 TR',
  },
  {
    id: 74,
    name: 'SQ GROUP',
    authority: 'SQ GROUP',
    capacity: '126 TR',
  },
  {
    id: 75,
    name: 'BEXIMCO PHARMACEUTICAL',
    authority: 'BAXIMCO GROUP',
    capacity: '202 TR',
  },
  {
    id: 76,
    name: 'TIMES MEDIA LTD',
    authority: 'HAMEEM GROUP',
    capacity: '1800 TR',
  },
  {
    id: 77,
    name: 'SQUARE PHARMACEUTICALS LTD.',
    authority: 'SQUARE PHARMACEUTICALS LTD.',
    capacity: '120 TR',
  },
  {
    id: 78,
    name: 'SAVAR NEWMARKET',
    authority: 'RP CONSTRUCTION PVT. LTD',
    capacity: '1500 TR',
  },
  {
    id: 79,
    name: 'BERGER PAINTS BANGLADESH LTD.(FACTORY)',
    authority: 'BERGER PAINTS BANGLADESH LTD.',
    capacity: '52 TR',
  },
  {
    id: 80,
    name: 'CYCLOTRON (16-20 MEV) AT THE ONCOLOGY BUILDING, BSMMU CAMPUS',
    authority: 'TRADE VISION',
    capacity: '120 TR',
  },
  {
    id: 81,
    name: 'BEACON PHARMA',
    authority: 'PRECISA TECHNO TRADE',
    capacity: '570 TR',
  },
  {
    id: 82,
    name: 'BEACON PHARMA',
    authority: 'CREST PROJECTS & PROFESSIONALS',
    capacity: '270 TR',
  },
  {
    id: 83,
    name: 'BEXIMCO PHARMACEUTICAL',
    authority: 'CLEAN AIR INNOVATION CO., LTD.',
    capacity: '2700 TR',
  },
  {
    id: 84,
    name: 'OPSONIN PHARMACEUTICALS LIMITED',
    authority: 'IMPERIAL CORPORATION LIMITED',
    capacity: '3925 TR',
  },
  {
    id: 85,
    name: 'OPSONIN PHARMACEUTICALS LIMITED',
    authority: 'IMPERIAL CORPORATION LIMITED',
    capacity: '650 TR',
  },
  {
    id: 86,
    name: 'JAMUNA BANK',
    authority: 'JAMUNA BANK',
    capacity: '600 TR',
  },
  {
    id: 87,
    name: 'EASTERN PLAZA SHOPPING COMPLEX',
    authority: 'EASTERN HOUSING LIMITED',
    capacity: '500 TR',
  },
  {
    id: 88,
    name: 'OPPO MOBILE FACTORY',
    authority: 'OPPO BANGLADESH HEAD OFFICE',
    capacity: '115 TR',
  },
  {
    id: 89,
    name: 'VITACAN',
    authority: 'VITACAN',
    capacity: '100 TR',
  },
  {
    id: 90,
    name: 'AGA KHAN ACADEMY (AKA) (3A&3B)',
    authority: 'AGA KHAN FOUNDATION (BANGLADESH)',
    capacity: '800 TR',
  },
  {
    id: 91,
    name: 'AUTOGRAPH',
    authority: 'SAYED KHUKON PROPERTIES LTD.',
    capacity: '900 TR',
  },
  {
    id: 92,
    name: 'FELICITY BIGDATA, I LIMITED (FBD-I)',
    authority: 'FELICITY BIGDATA, I LIMITED',
    capacity: '636 TR',
  },
  {
    id: 93,
    name: 'NICE SYNTHETIC YARN MILLS LTD',
    authority: 'NICE SYNTHETIC YARN MILLS LTD',
    capacity: '800 TR',
  },
  {
    id: 94,
    name: 'RANGS PHARMACEUTICALS LIMITED',
    authority: 'TRIPS ASSOCIATES PVT. LTD',
    capacity: '350 TR',
  },
  {
    id: 95,
    name: 'BEACON PHARMA',
    authority: 'PRECISA TECHNO TRADE',
    capacity: '850 TR',
  },
  {
    id: 96,
    name: 'COAST TO COAST PHARMA LIMITED (C2C PHARMA)',
    authority: 'PRECISA TECHNO TRADE',
    capacity: '400 TR',
  },
  {
    id: 97,
    name: 'JULPHAR BANGLADESH LTD.',
    authority: 'PRECISA TECHNO TRADE',
    capacity: '65 TR',
  },
  {
    id: 98,
    name: 'SQUARE PHARMACEUTICALS LTD.',
    authority: 'SQUARE PHARMACEUTICALS LTD.',
    capacity: '405 TR',
  },
  {
    id: 99,
    name: 'GLOBEX TEXTILE CO., LTD',
    authority: 'TRIPS ASSOCIATES PVT. LTD',
    capacity: '224 TR',
  },
  {
    id: 100,
    name: 'BEXIMCO SYNTHETICS LIMITED',
    authority: 'BEXIMCO SYNTHETICS LIMITED',
    capacity: '270 TR',
  },
  {
    id: 101,
    name: 'R-PAC BANGLADESH LTD',
    authority: 'R-PAC (BANGLADESH) LTD.',
    capacity: '227 TR',
  },
  {
    id: 102,
    name: 'PAXAR BANGLADESH LTD.',
    authority: 'PAXAR BANGLADESH LTD.',
    capacity: '200 TR',
  },
  {
    id: 103,
    name: 'PAXAR BANGLADESH LTD.',
    authority: 'PAXAR BANGLADESH LTD.',
    capacity: '24 TR',
  },
  {
    id: 104,
    name: 'APEX PHARMA LTD.',
    authority: 'APEX PHARMA LTD.',
    capacity: '37 TR',
  },
  {
    id: 105,
    name: 'APEX PHARMA LTD.',
    authority: 'APEX PHARMA LTD.',
    capacity: '311 TR',
  },
  {
    id: 106,
    name: 'SQUARE PHARMACEUTICALS LTD.',
    authority: 'SQUARE PHARMACEUTICALS LTD.',
    capacity: '240 TR',
  },
  {
    id: 107,
    name: 'GENTRY PHARMACEUTICALS LTD',
    authority: 'GENTRY PHARMACEUTICALS LTD',
    capacity: '102 TR',
  },
  {
    id: 108,
    name: 'SQUARE PHARMACEUTICALS LTD.',
    authority: 'SQUARE PHARMACEUTICALS LTD.',
    capacity: '38 TR',
  },
  {
    id: 109,
    name: 'ROOPPUR NUCLEAR POWER PLANT',
    authority: 'JSC ESKM BD LTD',
    capacity: '561 TR',
  },
  {
    id: 110,
    name: 'ROOPPUR NUCLEAR POWER PLANT',
    authority: 'JSC ESKM BD LTD',
    capacity: '34 TR',
  },
  {
    id: 111,
    name: 'ROOPPUR NUCLEAR POWER PLANT',
    authority: 'JSC ESKM BD LTD',
    capacity: '253 TR',
  },
  {
    id: 112,
    name: 'ARGON SPINNING MILLS',
    authority: 'ARGON DENIM LTD.',
    capacity: '300 TR',
  },
  {
    id: 113,
    name: 'SQUARE PHARMACEUTICALS LTD.',
    authority: 'SQUARE PHARMACEUTICALS LTD.',
    capacity: '300 TR',
  },
  {
    id: 114,
    name: 'SQUARE PHARMACEUTICALS LTD.',
    authority: 'SQUARE PHARMACEUTICALS LTD.',
    capacity: '213 TR',
  },
  {
    id: 115,
    name: 'VITALAC',
    authority: 'VITALAC',
    capacity: '100 TR',
  },
  {
    id: 116,
    name: 'ESTABLISHMENT OF A SUPER SPECIALIZED HOSPITAL UNDER BSMMU',
    authority: 'HYUNDAI DEVELOPMENT COMPANY (HDC)',
    capacity: '1100 TR',
  },
  {
    id: 117,
    name: 'ESKAYEF PHARMACEUTICALS LIMITED',
    authority: 'ESKAYEF PHARMACEUTICALS LIMITED',
    capacity: '300 TR',
  },
  {
    id: 118,
    name: 'ESKAYEF PHARMACEUTICALS LIMITED',
    authority: 'ESKAYEF PHARMACEUTICALS LIMITED',
    capacity: '600 TR',
  },
  {
    id: 119,
    name: 'ESKAYEF PHARMACEUTICALS LIMITED',
    authority: 'ESKAYEF PHARMACEUTICALS LIMITED',
    capacity: '300 TR',
  },
  {
    id: 120,
    name: 'BEACON PHARMA (EREBA PROJECT)',
    authority: 'PRECISA TECHNO TRADE',
    capacity: '450 TR',
  },
  {
    id: 121,
    name: 'BEACON PHARMA (WARE HOUSE PROJECT)',
    authority: 'PRECISA TECHNO TRADE',
    capacity: '300 TR',
  },
  {
    id: 122,
    name: 'PAXAR BANGLADESH LTD.',
    authority: 'PAXAR BANGLADESH LTD.',
    capacity: '600 TR',
  },
  {
    id: 123,
    name: 'Z. H. SIKDER SHOPPING COMPLEX',
    authority: 'SIKDER REAL ESTATE (PVT.) LTD.',
    capacity: '3600 TR',
  },
  {
    id: 124,
    name: 'MRT LINE 6 UNDER DHAKA MASS RAPID TRANSIT DEVELOPMENT (CP-02, BUILDING – 32, OCC)',
    authority: 'DHAKA MASS TRANSIT COMPANY LIMITED',
    capacity: '170 TR',
  },
  {
    id: 125,
    name: 'THE ACME LABORATORIES LTD.',
    authority: 'THE ACME LABORATORIES LTD.',
    capacity: '250 TR',
  },
  {
    id: 126,
    name: 'MRT LINE 6 UNDER DHAKA MASS RAPID TRANSIT DEVELOPMENT (CP-02, B – 32, ADMIN)',
    authority: 'DHAKA MASS TRANSIT COMPANY LIMITED',
    capacity: '700 TR',
  },
  {
    id: 127,
    name: 'MRT LINE 6 UNDER DHAKA MASS RAPID TRANSIT DEVELOPMENT (CP-02, B – 33, TRAINING CENTRE)',
    authority: 'DHAKA MASS TRANSIT COMPANY LIMITED',
    capacity: '500 TR',
  },
  {
    id: 128,
    name: 'SQUARE PHARMACEUTICALS LTD.',
    authority: 'SQUARE PHARMACEUTICALS LTD.',
    capacity: '300 TR',
  },
  {
    id: 129,
    name: 'BERGER PAINTS BANGLADESH LTD.(FACTORY)',
    authority: 'BERGER PAINTS BANGLADESH LTD.',
    capacity: '56 TR',
  },
  {
    id: 130,
    name: 'INCEPTA VACCINE LIMITED',
    authority: 'INCEPTA CHEMICALS LIMITED',
    capacity: '75 TR',
  },
  {
    id: 131,
    name: "INTERNATIONAL CONFERENCE CENTRE (ICC) & PRIME MINISTER'S OFFICE",
    authority: 'BANGLADESH PUBLIC WORKS DEPARTMENT',
    capacity: '750 TR',
  },
  {
    id: 132,
    name: 'RESIDENCE OF HONORABLE VICE CHAIRMAN',
    authority: 'BASHUDHARA INDUSTRIAL HEADQUARTER-2',
    capacity: '65 TR',
  },
  {
    id: 133,
    name: 'CHECKPOINT SYSTEMS BANGLADESH LTD.',
    authority: 'AIRCON ENGINEERING LTD',
    capacity: '570 TR',
  },
  {
    id: 134,
    name: 'ACI PHARMACEUTICALS LIMITED',
    authority: 'TRIPS ASSOCIATES PVT. LTD',
    capacity: '150 TR',
  },
  {
    id: 135,
    name: 'INCEPTA CHEMICALS LIMITED',
    authority: 'INCEPTA CHEMICALS LIMITED',
    capacity: '40 TR',
  },
  {
    id: 136,
    name: 'APEX PHARMA LTD.',
    authority: 'APEX PHARMA LTD.',
    capacity: '200 TR',
  },
  {
    id: 137,
    name: 'MAA-O-SHI SHU-HOSPITAL',
    authority: 'MAA-O-SHI SHU-HOSPITAL',
    capacity: '848 TR',
  },
  {
    id: 138,
    name: 'PAXAR BANGLADESH LTD.',
    authority: 'PAXAR BANGLADESH LTD.',
    capacity: '80 TR',
  },
  {
    id: 139,
    name: 'HAZRAT SHAHJALAL INTERNATIONAL AIRPORT EXPANSION T3',
    authority: 'CIVIL AVIATION AUTHORITY, BANGLADESH (CAAB)',
    capacity: '14400 TR',
  },
  {
    id: 140,
    name: 'EVINCE TEXTILES LIMITED',
    authority: 'EVINCE TEXTILES LIMITED',
    capacity: '743 TR',
  },
  {
    id: 141,
    name: 'ESTABLISHMENT OF MUSLIM INSTITUTE CULTURAL COMPLEX, CHATTOGRAM',
    authority: 'PWD E/M DIVISION-2',
    capacity: '1350 TR',
  },
  {
    id: 142,
    name: 'ESKAYEF PHARMACEUTICALS LIMITED',
    authority: 'ESKAYEF PHARMACEUTICALS LIMITED',
    capacity: '300 TR',
  },
  {
    id: 143,
    name: 'AGA KHAN ACADEMY (AKA) – P5A',
    authority: 'AGA KHAN FOUNDATION (BANGLADESH)',
    capacity: '300 TR',
  },
  {
    id: 144,
    name: 'BASHUNDHARA TENT PROJECT (ICCB)',
    authority: 'BASHUDHARA INDUSTRIAL HEADQUARTER-2',
    capacity: '1380 TR',
  },
  {
    id: 145,
    name: 'AMAN WINTER WEARS LTD.',
    authority: 'UNIFILLGROUP',
    capacity: '600 TR',
  },
];
