import { Geist, Geist_Mono, Montserrat } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/Component/shared/Navber/Navber';
import Footer from '@/Component/shared/Footer/Footer';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const Mont_serrat = Montserrat({
  variable: '--font-montserrat',
  display: 'swap',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '900'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${Mont_serrat.variable} font-sans bg-white text-gray-900 dark:bg-gray-900 dark:text-gray-50`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
